[project]
name = "uc-intg-samsungtv"
version = "1.5.2"
description = "An Unfolded Circle integration for Samsung TV"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "async-timeout>=5.0.1",
    "pyee>=9.0.0",
    "samsungtvws==3.0.6",
    "ucapi==0.7.0",
    "ucapi-framework==1.9.7",
    "wakeonlan>=4.0.0",
    "aiohttp>=3.14.3,<4.0.0",
    "sddp-discovery-protocol==1.5.0",
    "pysmartthings==0.7.8",
    "certifi>=2026.7.0"
]
